@extends(Auth::user()->is_vendor === 1 ? 'vendorlayouts.layout' : 'userlayouts.layouts')

@section('container')
    <div class="container px-6 mx-auto grid">
        <div class="my-6">
            <h2 class="text-2xl font-semibold text-gray-700">Level Income Report</h2>
            <p class="text-sm text-gray-500 mt-1">Earnings from your downline structure</p>
        </div>

        <div class="w-full overflow-hidden rounded-xl shadow-sm border border-gray-100 bg-white">
            <div class="w-full overflow-x-auto">
                <table class="w-full whitespace-no-wrap">
                    <thead>
                        <tr
                            class="text-xs font-semibold tracking-wide text-left text-gray-500 uppercase border-b bg-gray-50">
                            <th class="px-4 py-3">Transaction Date</th>
                            <th class="px-4 py-3">Generated By</th>
                            <th class="px-4 py-3 text-center">Level</th>
                            <th class="px-4 py-3 text-right">Business (PV)</th>
                            <th class="px-4 py-3 text-right">Amount</th>
                        </tr>
                    </thead>
                    <tbody class="bg-white divide-y divide-gray-100">
                        @forelse($incomes as $income)
                            <tr class="text-gray-700 hover:bg-gray-50 transition-colors">
                                <td class="px-4 py-3 text-sm">
                                    <p class="font-semibold">{{ $income->created_at->format('d M Y') }}</p>
                                    <p class="text-xs text-gray-600">{{ $income->created_at->format('h:i A') }}</p>
                                </td>
                                <td class="px-4 py-3 text-sm">
                                    <div class="flex items-center">
                                        <div
                                            class="w-8 h-8 rounded-full bg-indigo-50 text-indigo-600 flex items-center justify-center mr-3 text-xs font-bold">
                                            {{ substr($income->from_user_name, 0, 1) }}
                                        </div>
                                        <div>
                                            <p class="font-medium text-gray-800">{{ $income->from_user_name }}</p>
                                            <p class="text-xs text-gray-500">{{ $income->from_user_ulid }}</p>
                                        </div>
                                    </div>
                                </td>
                                <td class="px-4 py-3 text-sm text-center">
                                    <span
                                        class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-indigo-100 text-indigo-800">
                                        L-{{ $income->level }}
                                    </span>
                                </td>
                                <td class="px-4 py-3 text-sm text-right text-gray-600">
                                    {{ $income->purchase_pv }}
                                </td>
                                <td class="px-4 py-3 text-sm text-right font-bold text-emerald-600">
                                    ₹{{ number_format($income->amount, 2) }}
                                </td>
                            </tr>
                        @empty
                            <tr>
                                <td colspan="5" class="px-4 py-8 text-center text-gray-500">
                                    No level income data available.
                                </td>
                            </tr>
                        @endforelse
                    </tbody>
                </table>
            </div>
            <div class="px-4 py-3 border-t bg-gray-50">
                {{ $incomes->links('pagination::bootstrap-5') }}
            </div>
        </div>
    </div>
@endsection
